package yamugapart.entity;
// Generated 24.Ara.2014 13:47:28 by Hibernate Tools 3.6.0



/**
 * Dlist generated by hbm2java
 */
public class Dlist  implements java.io.Serializable {


     private Integer dlistId;
     private String dlistTuru;
     private String dlistMarka;
     private String dlistAdet;
     private int dlistApartId;

    public Dlist() {
    }

	
    public Dlist(int dlistApartId) {
        this.dlistApartId = dlistApartId;
    }
    public Dlist(String dlistTuru, String dlistMarka, String dlistAdet, int dlistApartId) {
       this.dlistTuru = dlistTuru;
       this.dlistMarka = dlistMarka;
       this.dlistAdet = dlistAdet;
       this.dlistApartId = dlistApartId;
    }
   
    public Integer getDlistId() {
        return this.dlistId;
    }
    
    public void setDlistId(Integer dlistId) {
        this.dlistId = dlistId;
    }
    public String getDlistTuru() {
        return this.dlistTuru;
    }
    
    public void setDlistTuru(String dlistTuru) {
        this.dlistTuru = dlistTuru;
    }
    public String getDlistMarka() {
        return this.dlistMarka;
    }
    
    public void setDlistMarka(String dlistMarka) {
        this.dlistMarka = dlistMarka;
    }
    public String getDlistAdet() {
        return this.dlistAdet;
    }
    
    public void setDlistAdet(String dlistAdet) {
        this.dlistAdet = dlistAdet;
    }
    public int getDlistApartId() {
        return this.dlistApartId;
    }
    
    public void setDlistApartId(int dlistApartId) {
        this.dlistApartId = dlistApartId;
    }




}


