package yamugapart.entity;
// Generated 24.Ara.2014 13:47:28 by Hibernate Tools 3.6.0



/**
 * Musteri generated by hbm2java
 */
public class Musteri  implements java.io.Serializable {


     private Integer musteriId;
     private String musteriAdi;
     private String musteriSoyadi;
     private String musteriTel;
     private String musteriEmail;
     private String musteriKiraTarihi;
     private int musteriApartId;
     private String musteriOdaNo;
     private String musteriDogalgaz;
     private String musteriSu;
     private String musteriInternet;
     private String musteriElektrik;

    public Musteri() {
    }

	
    public Musteri(String musteriTel, int musteriApartId) {
        this.musteriTel = musteriTel;
        this.musteriApartId = musteriApartId;
    }
    public Musteri(String musteriAdi, String musteriSoyadi, String musteriTel, String musteriEmail, String musteriKiraTarihi, int musteriApartId, String musteriOdaNo, String musteriDogalgaz, String musteriSu, String musteriInternet, String musteriElektrik) {
       this.musteriAdi = musteriAdi;
       this.musteriSoyadi = musteriSoyadi;
       this.musteriTel = musteriTel;
       this.musteriEmail = musteriEmail;
       this.musteriKiraTarihi = musteriKiraTarihi;
       this.musteriApartId = musteriApartId;
       this.musteriOdaNo = musteriOdaNo;
       this.musteriDogalgaz = musteriDogalgaz;
       this.musteriSu = musteriSu;
       this.musteriInternet = musteriInternet;
       this.musteriElektrik = musteriElektrik;
    }
   
    public Integer getMusteriId() {
        return this.musteriId;
    }
    
    public void setMusteriId(Integer musteriId) {
        this.musteriId = musteriId;
    }
    public String getMusteriAdi() {
        return this.musteriAdi;
    }
    
    public void setMusteriAdi(String musteriAdi) {
        this.musteriAdi = musteriAdi;
    }
    public String getMusteriSoyadi() {
        return this.musteriSoyadi;
    }
    
    public void setMusteriSoyadi(String musteriSoyadi) {
        this.musteriSoyadi = musteriSoyadi;
    }
    public String getMusteriTel() {
        return this.musteriTel;
    }
    
    public void setMusteriTel(String musteriTel) {
        this.musteriTel = musteriTel;
    }
    public String getMusteriEmail() {
        return this.musteriEmail;
    }
    
    public void setMusteriEmail(String musteriEmail) {
        this.musteriEmail = musteriEmail;
    }
    public String getMusteriKiraTarihi() {
        return this.musteriKiraTarihi;
    }
    
    public void setMusteriKiraTarihi(String musteriKiraTarihi) {
        this.musteriKiraTarihi = musteriKiraTarihi;
    }
    public int getMusteriApartId() {
        return this.musteriApartId;
    }
    
    public void setMusteriApartId(int musteriApartId) {
        this.musteriApartId = musteriApartId;
    }
    public String getMusteriOdaNo() {
        return this.musteriOdaNo;
    }
    
    public void setMusteriOdaNo(String musteriOdaNo) {
        this.musteriOdaNo = musteriOdaNo;
    }
    public String getMusteriDogalgaz() {
        return this.musteriDogalgaz;
    }
    
    public void setMusteriDogalgaz(String musteriDogalgaz) {
        this.musteriDogalgaz = musteriDogalgaz;
    }
    public String getMusteriSu() {
        return this.musteriSu;
    }
    
    public void setMusteriSu(String musteriSu) {
        this.musteriSu = musteriSu;
    }
    public String getMusteriInternet() {
        return this.musteriInternet;
    }
    
    public void setMusteriInternet(String musteriInternet) {
        this.musteriInternet = musteriInternet;
    }
    public String getMusteriElektrik() {
        return this.musteriElektrik;
    }
    
    public void setMusteriElektrik(String musteriElektrik) {
        this.musteriElektrik = musteriElektrik;
    }




}


